######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 22 13:47:40 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += randomized_queue.h
SOURCES += Subset.cpp
