######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 26 09:13:06 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += deque.h
SOURCES += testForDeque.cpp
