######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 25 14:32:21 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += randomized_queue.h
SOURCES += testForRandomizedQueue.cpp
